#!/bin/bash
# modified by shazeya@syafi.com (NL130240)
# modified for Cronus Remake by RoM.

./cronus-start iniciar
sleep 30

while [ true ]; do
    if [ "      0" = "$(ps | grep -e log | wc -l)" ] ||
       [ "      0" = "$(ps | grep -e char  | wc -l)" ] ||
       [ "      0" = "$(ps | grep -e map   | wc -l)" ]; then
        printf "Erro:"
        date
        sleep 10
        printf "Checando:"
        date
        if [ "      0" = "$(ps | grep -e log | wc -l)" ] ||
           [ "      0" = "$(ps | grep -e char  | wc -l)" ] ||
           [ "      0" = "$(ps | grep -e map   | wc -l)" ]; then
            printf "Confirmação do Erro:"
            date
            printf "Restauração:"
            date
            ./cronus-start iniciar
        else
            printf "Check Miss Sorry:"
            date
        fi
    fi
    sleep 10
done
