<?php
return array(
	pow(2,  0) => 'Aprendiz',
	pow(2,  1) => 'Espadachim',
	pow(2,  2) => 'Mago',
	pow(2,  3) => 'Arqueiro',
	pow(2,  4) => 'Noviço',
	pow(2,  5) => 'Mercador',
	pow(2,  6) => 'Gatuno',
	pow(2,  7) => 'Cavaleiro',
	pow(2,  8) => 'Sacerdote',
	pow(2,  9) => 'Bruxo',
	pow(2, 10) => 'Ferreiro',
	pow(2, 11) => 'Caçador',
	pow(2, 12) => 'Mercenário',
	pow(2, 13) => 'Não Utilizado',
	pow(2, 14) => 'Templário',
	pow(2, 15) => 'Monge',
	pow(2, 16) => 'Sábio',
	pow(2, 17) => 'Arruaceiro',
	pow(2, 18) => 'Alquimista',
	pow(2, 19) => 'Bardo/Odalisca',
	pow(2, 20) => 'Não Utilizado',
	pow(2, 21) => 'Taekwon',
	pow(2, 22) => 'Mestre Taekwon',
	pow(2, 23) => 'Espiritualista',
	pow(2, 24) => 'Justiceiro',
	pow(2, 25) => 'Ninja',
	pow(2, 26) => 'Gangsi',
	pow(2, 27) => 'Death Knight',
	pow(2, 28) => 'Dark Collector',
	pow(2, 29) => 'Kagerou/Oboro'
)
?>